### PR TITLE
Disallow shouts with user tags

### PR DESCRIPTION
**Pull request by bhammerslag**
I still haven't figured out how to properly test Agimus changes (I am the undisputed champ of saying "I should learn about containers" and then not doing it), but hopefully this change is simple enough.

### CODE REVIEW

**Review by zmattingly — COMMENTED** [review]
Ayy thanks, I've been draggin my feet on getting this nebulous PR pushed and I had something similar in place.

The usage fo `re.sub()` compared to the original message is interesting. I was just going to do an `re.search()` and if it catches a tag anywhere in the string it'd just fail. Kinda 6 of one, half dozen of another, as they'll both accomplish the same thing so I'm not necessarily opposed to it just curious about the approach!

**Comment by bhammerslag** [comment]
Well you see my approach is based on being a python novice, so if I can reuse good code and avoid new bugs I'll usually do that. 

Your approach will certainly be faster; I'll reimplement with re.search() unless you just want to do it yourself in an omnibus PR.

**Comment by zmattingly** [comment]
Fire away! Mine will continue limping on for now.

**Comment by bhammerslag** [comment]
@zmattingly Updated with re.search()

On the one hand this has taught me about the useful python concept of things being "truthy", on the other hand I don't like it philosophically!

**Comment by mathew-fleisch** [comment]
@bhammerslag you'll probably need to PR from a branch and not a fork to get the tests to pass.

**Pull request merged**
